spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
  
  h2:
    console:
      enabled: true

  flyway:
    enabled: false

mcp:
  security:
    enabled: false

server:
  port: 5005

logging:
  level:
    com.zamaz.mcp: DEBUG